# Generated by Django 5.0.3 on 2024-12-04 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_advertisement_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='likes',
            field=models.ManyToManyField(related_name='board.Advertisement+', to=settings.AUTH_USER_MODEL),
        ),
    ]
