# Generated by Django 5.0.3 on 2024-12-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_alter_advertisement_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='dislikes',
        ),
    ]
