# Generated by Django 5.0.3 on 2024-12-04 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_remove_advertisement_dislikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='dislikes',
            field=models.ManyToManyField(related_name='Advertisement.post+', to=settings.AUTH_USER_MODEL),
        ),
    ]
